function data=loadexp(name)
global datasetname
saved=load(sprintf('./data/%s/%s.mat',datasetname,name));
% data=saved.simout.data;
data=struct(...
    'time',saved.simout.time,...
    'alpha',saved.simout.data(:,2),...
    'theta',saved.simout.data(:,3),...
    'u',saved.simout.data(:,1),...
    'y',saved.simout.data(:,2:3)...
);