function xnext = generated_nonlineuler(in1,u,step)
%GENERATED_NONLINEULER
%    XNEXT = GENERATED_NONLINEULER(IN1,U,STEP)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Oct-2022 01:39:02

alpha = in1(1,:);
alpha_dot = in1(3,:);
theta = in1(2,:);
theta_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = alpha_dot.^2;
t5 = theta.*2.0;
t6 = theta_dot.^2;
t7 = t2.^2;
t8 = sin(t5);
t9 = t3.^3;
t10 = -t9;
t12 = t7.*3.618472965246204e+22;
t11 = t3+t10;
t13 = t12-5.437212896706948e+22;
t14 = 1.0./t13;
et1 = alpha.*5.032826210861381e+41+alpha_dot.*6.370860140842386e+40-t8.*8.546551487743521e+41-u.*2.102880476441784e+43;
et2 = t3.*t6.*-1.428781288470884e+40+t4.*t11.*1.428781288470884e+40-t2.*theta_dot.*1.416598541018128e+39+alpha_dot.*t8.*theta_dot.*1.378353713583677e+40;
et3 = t3.*1.093398116977154e+63+theta_dot.*9.061585713741194e+59+t3.*(t3.^2-1.0).*3.507615221030474e+62;
et4 = alpha.*t2.*-1.109719244775019e+62-alpha_dot.*t2.*1.404750692325785e+61-t4.*t8.*4.569757675439684e+60;
et5 = t6.*t8.*1.575204493420426e+60-t7.*theta_dot.*2.906951775631697e+59+t2.*u.*4.636772335060833e+63;
et6 = t2.^3.*t3.*t4.*2.931951560902129e+60-alpha_dot.*t11.*theta_dot.*6.078436162845877e+60;
xnext = [alpha+alpha_dot.*step;theta+step.*theta_dot;alpha_dot+(step.*t14.*(et1+et2))./7.90224914123014e+17;theta_dot+(step.*t14.*(et3+et4+et5+et6))./1.680919162906923e+38];
