function xnext = generated_nonlineuler(in1,u,step)
%GENERATED_NONLINEULER
%    XNEXT = GENERATED_NONLINEULER(IN1,U,STEP)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Oct-2022 21:30:40

alpha = in1(1,:);
alpha_dot = in1(3,:);
theta = in1(2,:);
theta_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = t2.^2;
t6 = t5.*7.496872083706022e+20;
t7 = t6-1.4771831809549e+21;
t8 = 1.0./t7;
et1 = alpha.*-1.006565242172276e+41-alpha_dot.*1.274172028168477e+40+u.*4.205760952883568e+42+t2.*t3.*3.418620595097408e+41;
et2 = t3.*t4.*2.857562576941768e+39+t2.*theta_dot.*2.833197082036257e+38;
et3 = t3.*2.970546379496425e+61+theta_dot.*2.461853575243799e+58-alpha.*t2.*4.438876979100076e+60;
et4 = alpha_dot.*t2.*-5.619002769303141e+59+t2.*u.*1.854708934024333e+62+t2.*t3.*t4.*1.26016359473634e+59;
xnext = [alpha+alpha_dot.*step;theta+step.*theta_dot;alpha_dot-(step.*t8.*(et1+et2))./3.95112457061507e+18;theta_dot+(step.*t8.*(et3+et4))./1.680919162906923e+38];
