function x_ddot = generated_nonlinfit(alpha,theta,alpha_dot,theta_dot,u)
%GENERATED_NONLINFIT
%    X_DDOT = GENERATED_NONLINFIT(ALPHA,THETA,ALPHA_DOT,THETA_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Oct-2022 11:58:04

t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = t2.^2;
t6 = t5.*5.202e-4;
t7 = t6-1.033684280825389e-3;
t8 = 1.0./t7;
et1 = alpha.*(-1.114482127011352e-2)-alpha_dot.*1.457479237134593e-3+u.*5.145679542825577e-1;
et2 = t2.*t3.*4.388810825838219e-2+t3.*t4.*3.668526888060489e-4+t2.*theta_dot.*3.637246567579307e-5;
et3 = t3.*8.895381886637765e-5;
et4 = theta_dot.*7.372087455672215e-8-alpha.*t2.*1.136771769551579e-5;
et5 = alpha_dot.*t2.*(-1.486628821877285e-6)+t2.*u.*5.248593133682088e-4+t2.*t3.*t4.*3.741897425821699e-7;
x_ddot = [t8.*(et1+et2).*(-1.367960533786131);t8.*(et3+et4+et5).*1.390203794498101e+3];
