function x_ddot = generated_nonlinfit(in1,in2,u)
%GENERATED_NONLINFIT
%    X_DDOT = GENERATED_NONLINFIT(IN1,IN2,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    27-Oct-2022 17:15:07

alpha = in1(1,:);
alpha_dot = in2(1,:);
theta = in1(2,:);
theta_dot = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = t2.^2;
t6 = t5.*5.202e-4;
t7 = t6-1.025001693833136e-3;
t8 = 1.0./t7;
et1 = alpha.*(-1.861030296237031e-2)-alpha_dot.*2.355809725319066e-3+u.*7.77600286783636e-1;
et2 = t2.*t3.*6.320663233735892e-2+t3.*t4.*5.283327065915832e-4+t2.*theta_dot.*5.238277876180678e-5;
et3 = t3.*1.270331474652572e-4;
et4 = theta_dot.*1.052792881539968e-7-alpha.*t2.*1.898250902161771e-5;
et5 = alpha_dot.*t2.*(-2.402925919825447e-6)+t2.*u.*7.931522925193087e-4+t2.*t3.*t4.*5.388993607234149e-7;
x_ddot = [t8.*(et1+et2).*(-9.498560163679913e-1);t8.*(et3+et4+et5).*9.653008296422676e+2];
