function xnext = generated_nonlineuler(in1,u,step)
%GENERATED_NONLINEULER
%    XNEXT = GENERATED_NONLINEULER(IN1,U,STEP)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    27-Oct-2022 21:17:33

alpha = in1(1,:);
alpha_dot = in1(3,:);
theta = in1(2,:);
theta_dot = in1(4,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = t2.^2;
t6 = t5.*1.41607583803336e+21;
t7 = t6-3.1935417637039e+21;
t8 = 1.0./t7;
et1 = alpha.*-1.006565242172276e+41-alpha_dot.*1.274172028168477e+40+u.*4.205760952883568e+42+t2.*t3.*4.946945096435073e+41;
et2 = t3.*t4.*1.36465659451413e+39+t2.*theta_dot.*4.099802836358348e+38;
et3 = t3.*1.579827576821562e+63+theta_dot.*1.309289158086209e+60-alpha.*t2.*1.425372718844358e+62;
et4 = alpha_dot.*t2.*-1.804324222587342e+61+t2.*u.*5.955676465922581e+63+t2.*t3.*t4.*1.932457230704348e+60;
xnext = [alpha+alpha_dot.*step;theta+step.*theta_dot;alpha_dot-(step.*t8.*(et1+et2))./1.445533379493318e+18;theta_dot+(step.*t8.*(et3+et4))./1.36465659451413e+39];
