function x_ddot = generated_nonlinfit(in1,in2,u)
%GENERATED_NONLINFIT
%    X_DDOT = GENERATED_NONLINFIT(IN1,IN2,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    27-Oct-2022 21:17:32

alpha = in1(1,:);
alpha_dot = in2(1,:);
theta = in1(2,:);
theta_dot = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = t2.^2;
t6 = t5.*4.4217e-5;
t7 = t6-9.971841364217159e-5;
t8 = 1.0./t7;
et1 = alpha.*(-1.861031175243817e-2)-alpha_dot.*2.355807420816275e-3+u.*7.776000919769337e-1;
et2 = t2.*t3.*9.146370906685353e-2+t3.*t4.*2.523103679213063e-4+t2.*theta_dot.*7.580095726681214e-5;
et3 = t3.*1.52010266232929e-6;
et4 = theta_dot.*1.259791868534091e-9;
et5 = alpha.*t2.*(-1.371486924595931e-7)-alpha_dot.*t2.*1.736112278770554e-8;
et6 = t2.*u.*5.730523877824013e-6+t2.*t3.*t4.*1.859401256396067e-9;
x_ddot = [t8.*(et1+et2).*(-1.168322976295368e-1);t8.*(et3+et4+et5+et6).*2.378023562579622e+4];
